version: '3'

services:
    app:
        build: 
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
        command: sleep infinity

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: bookstore
        ports:
            - "3306:3306"
